version: '3'
services:
   db:
     image: mysql:latest
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: dev
       MYSQL_DATABASE: dev
       MYSQL_USER: dev
       MYSQL_PASSWORD: dev

   web:
     depends_on:
       - db
     build: .
     ports:
       - "8000:80"
     restart: always
     volumes:
       - .:/var/www
     environment:
       DB_HOST: db:3306
       DB_USER: dev
       DB_PASSWORD: dev
volumes:
  db_data:
  .: